require './lib/connect_four'

def row_win_check (board)
  board.update("O", 2)
  board.update("O", 3)
  board.update("O", 4)
  board.update("O", 5)
  board.update("X", 2)
  board.update("X", 3)
  board.update("X", 4)
  board.update("X", 2)
end

def ve_di_win_fill (board)
board.update("X", 3)
board.update("O", 3)
board.update("X", 3)
board.update("O", 4)
board.update("X", 4)
board.update("X", 4)
board.update("X", 5)
board.update("O", 5)
board.update("X", 1)
board.update("X", 1)
board.update("X", 1)
board.update("O", 1)
board.update("X", 7)
board.update("X", 7)
board.update("X", 6)
board.update("X", 6)
board.update("X", 6)
board.update("X", 6)
board.update("X", 2)
board.update("X", 2)
board.update("O", 2)
end